### ISSUE TITLE
First binding of KiCAD plugin fails

### ISSUE THREAD

**Issue by mawildoer** [atopile/atopile#108]
<img width="720" alt="Screenshot 2024-02-07 at 08 05 18" src="https://github.com/atopile/atopile/assets/4241578/86707262-4b7f-4d18-955f-38c6415d7b0e">

```
plugboard\src\atopile on  main [?] ❯ ato create
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\aranwe\AppData\Roaming\Python\Python312\Scripts\ato.exe\__main__.py", line 7, in <module>
  File "C:\Users\aranwe\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aranwe\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\aranwe\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1685, in invoke
    super().invoke(ctx)
...
  File "C:\Users\aranwe\AppData\Roaming\Python\Python312\site-packages\atopile\cli\do_configure.py", line 58, in install_kicad_plugin
    with (kicad_plugin_dir / "atopile.py").open("w", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\pathlib.py", line 1013, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\aranwe\\Documents\\KiCad\\7.0\\scripting\\plugins\\atopile.py'`

```

**Comment by mawildoer** [comment]
#113 should fix this!
