### ISSUE TITLE
Zero ohm resistors cause a compiler crash

### ISSUE THREAD

**Issue by hollinsky** [atopile/atopile#124]
Now that I updated to 0.2.8, it seems generating the tolerance percentage is diving by the nominal value of a zero ohm resistor, causing a divide by zero.

The code in `front_end.py` doing the unchecked divide has been around for a while but it looks like a05c07c0bac7ab699effc3a6c175adbcd2b43099 actually started calling `Physical.to_dict` which exposes the error.

```
Traceback (most recent call last):
  File "./venv/bin/ato", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "./venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/errors.py", line 268, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/cli/common.py", line 134, in wrapper
    return f(*args, **kwargs, build_ctxs=build_ctxs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/errors.py", line 268, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/cli/build.py", line 38, in build
    _do_build(build_ctx)
  File "./venv/lib/python3.11/site-packages/atopile/cli/build.py", line 76, in _do_build
    muster.targets[target_name](build_ctx)
  File "./venv/lib/python3.11/site-packages/atopile/cli/build.py", line 105, in wrapper
    return func(build_args)
           ^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/cli/build.py", line 133, in generate_netlist
    f.write(get_netlist_as_str(build_args.entry))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/netlist.py", line 156, in get_netlist_as_str
    netlist = builder.build(root)
              ^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/netlist.py", line 127, in build
    components.get_footprint(component)
  File "./venv/lib/python3.11/site-packages/atopile/components.py", line 316, in get_footprint
    db_data = _get_generic_from_db(addr)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/components.py", line 134, in _get_generic_from_db
    specd_data_dict = {
                      ^
  File "./venv/lib/python3.11/site-packages/atopile/components.py", line 135, in <dictcomp>
    k: v.to_dict() if isinstance(v, Physical) else v for k, v in specd_data.items()
       ^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/front_end.py", line 111, in to_dict
    "tolerance_pct": self.tolerance_pct,
                     ^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/front_end.py", line 98, in tolerance_pct
    return self.tolerance / self.nominal * 100
           ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
ZeroDivisionError: float division by zero
```

**Comment by mawildoer** [comment]
Thanks again mate! https://github.com/atopile/atopile/pull/130
