### ISSUE TITLE
Invalid replacements cause a compiler crash

### ISSUE THREAD

**Issue by hollinsky** [atopile/atopile#125]
Rather than the typical "key error, couldn't find" message, when a replacement has a typo or is not imported, the error causes a compiler crash:

```
           INFO     Building netlist                                                                                                                                           build.py:74
Traceback (most recent call last):
  File "./venv/bin/ato", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "./venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/errors.py", line 268, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/cli/common.py", line 134, in wrapper
    return f(*args, **kwargs, build_ctxs=build_ctxs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/errors.py", line 268, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/cli/build.py", line 38, in build
    _do_build(build_ctx)
  File "./venv/lib/python3.11/site-packages/atopile/cli/build.py", line 76, in _do_build
    muster.targets[target_name](build_ctx)
  File "./venv/lib/python3.11/site-packages/atopile/cli/build.py", line 105, in wrapper
    return func(build_args)
           ^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/cli/build.py", line 133, in generate_netlist
    f.write(get_netlist_as_str(build_args.entry))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/netlist.py", line 156, in get_netlist_as_str
    netlist = builder.build(root)
              ^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/netlist.py", line 121, in build
    all_components = list(filter(match_components, all_descendants(root)))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/instance_methods.py", line 44, in all_descendants
    for child in get_children(addr):
  File "./venv/lib/python3.11/site-packages/atopile/instance_methods.py", line 10, in get_children
    root_instance = lofty.get_instance_tree(root_addr)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/front_end.py", line 892, in get_instance_tree
    self.make_instance(addr, obj_layer)
  File "./venv/lib/python3.11/site-packages/atopile/front_end.py", line 974, in make_instance
    self.visitBlock(super_obj_.src_ctx)
  File "./venv/lib/python3.11/site-packages/atopile/front_end.py", line 392, in visitBlock
    return self.visit_iterable_helper(ctx.stmt())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/front_end.py", line 301, in visit_iterable_helper
    child_results = list(item for item in child_results if item is not NOTHING)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/front_end.py", line 301, in <genexpr>
    child_results = list(item for item in child_results if item is not NOTHING)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/front_end.py", line 296, in __visit
    child_result = self.visit(child)
                   ^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
           ^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/parser/AtopileParser.py", line 367, in accept
    return visitor.visitStmt(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/front_end.py", line 376, in visitStmt
    stmt_returns = self.visitSimple_stmts(ctx.simple_stmts())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/front_end.py", line 388, in visitSimple_stmts
    return self.visit_iterable_helper(ctx.simple_stmt())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/front_end.py", line 301, in visit_iterable_helper
    child_results = list(item for item in child_results if item is not NOTHING)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/front_end.py", line 301, in <genexpr>
    child_results = list(item for item in child_results if item is not NOTHING)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/front_end.py", line 296, in __visit
    child_result = self.visit(child)
                   ^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
           ^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/parser/AtopileParser.py", line 524, in accept
    return visitor.visitSimple_stmt(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/front_end.py", line 1124, in visitSimple_stmt
    return super().visitSimple_stmt(ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/front_end.py", line 363, in visitSimple_stmt
    result = self.visitChildren(ctx)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/antlr4/tree/Tree.py", line 44, in visitChildren
    childResult = c.accept(self)
                  ^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/parser/AtopileParser.py", line 928, in accept
    return visitor.visitAssign_stmt(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/front_end.py", line 1028, in visitAssign_stmt
    self.make_instance(new_addr, actual_super)
  File "./venv/lib/python3.11/site-packages/atopile/front_end.py", line 965, in make_instance
    stack.enter_context(self.apply_replacements_from_objs(supers))
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 517, in enter_context
    result = _enter(cm)
             ^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/front_end.py", line 928, in apply_replacements_from_objs
    replace_with_addr = lookup_obj_in_closure(
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/front_end.py", line 758, in lookup_obj_in_closure
    raise KeyError(ref)
KeyError: ('IgnoreDebugPoint',)
```

**Comment by mawildoer** [comment]
Thanks for pointing this one out! Seems like it actually runs even a little deeper than that and the name lookup logic could crash out with bad exceptions. Fixed here: https://github.com/atopile/atopile/pull/129

Thanks @hollinsky !
