### ISSUE TITLE
Incorrect footprint crashes the compiler

### ISSUE THREAD

**Issue by hollinsky** [atopile/atopile#40]
I had a typo 'C0401' instead of 'C0402' and you can see the following error during `ato build`

```
Traceback (most recent call last):
  File "./venv/bin/ato", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "./venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/errors.py", line 247, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/cli/common.py", line 130, in wrapper
    return f(*args, **kwargs, build_ctxs=build_ctxs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/errors.py", line 247, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/cli/build.py", line 39, in build
    _do_build(build_ctx)
  File "./venv/lib/python3.11/site-packages/atopile/cli/build.py", line 61, in _do_build
    muster.targets[target_name](build_ctx)
  File "./venv/lib/python3.11/site-packages/atopile/cli/build.py", line 90, in wrapper
    return func(build_args)
           ^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/cli/build.py", line 118, in generate_netlist
    f.write(get_netlist_as_str(build_args.entry))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/netlist.py", line 167, in get_netlist_as_str
    netlist = builder.build(root)
              ^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/netlist.py", line 145, in build
    libsource = self._libparts[footprint] = self.make_libpart(
                                            ^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/netlist.py", line 71, in make_libpart
    part=_get_mpn(comp_addr),
         ^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/errors.py", line 339, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/components.py", line 161, in get_mpn
    return _get_generic_from_db(addr)["LCSC Part #"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venv/lib/python3.11/site-packages/atopile/components.py", line 122, in _get_generic_from_db
    filters.append(f"Package == '{_generics_to_db_fp_map[specd_data['footprint']]}'")
                                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'C0401'
```

**Comment by Timot05** [comment]
Fixed through PR: https://github.com/atopile/atopile/pull/45

<img width="1057" alt="Screenshot 2024-01-30 at 15 45 08" src="https://github.com/atopile/atopile/assets/9785003/5e49b06a-486a-4a20-9483-c84878da6a72">

**Comment by Timot05** [comment]
PR merged. Closing.
