### ISSUE TITLE
`ato --version` returns Typeerrror on fresh Windows Install

### ISSUE THREAD

**Issue by markwu2001** [atopile/atopile#490]
Occurs for Windows and macos fresh installation

```
PS C:\Users\keepi> python --version
Python 3.13.0
PS C:\Users\keepi> pipx install atopile
  installed package atopile 0.2.66, installed using Python 3.13.0
  These apps are now globally available
    - ato.exe
done! ✨ 🌟 ✨
PS C:\Users\keepi> ato --version
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\keepi\.local\bin\ato.exe\__main__.py", line 4, in <module>
    from atopile.cli.cli import cli
  File "C:\Users\keepi\pipx\venvs\atopile\Lib\site-packages\atopile\cli\cli.py", line 11, in <module>
    from . import build, configure, create, inspect, install, view
  File "C:\Users\keepi\pipx\venvs\atopile\Lib\site-packages\atopile\cli\build.py", line 10, in <module>
    import atopile.assertions
  File "C:\Users\keepi\pipx\venvs\atopile\Lib\site-packages\atopile\assertions.py", line 11, in <module>
    import pint
  File "C:\Users\keepi\pipx\venvs\atopile\Lib\site-packages\pint\__init__.py", line 18, in <module>
    from .delegates.formatter._format_helpers import formatter
  File "C:\Users\keepi\pipx\venvs\atopile\Lib\site-packages\pint\delegates\__init__.py", line 12, in <module>
    from . import txt_defparser
  File "C:\Users\keepi\pipx\venvs\atopile\Lib\site-packages\pint\delegates\txt_defparser\__init__.py", line 12, in <module>
    from .defparser import DefParser
  File "C:\Users\keepi\pipx\venvs\atopile\Lib\site-packages\pint\delegates\txt_defparser\defparser.py", line 10, in <module>
    from . import block, common, context, defaults, group, plain, system
  File "C:\Users\keepi\pipx\venvs\atopile\Lib\site-packages\pint\delegates\txt_defparser\common.py", line 23, in <module>
    @dataclass(frozen=True)
     ~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\keepi\AppData\Local\Programs\Python\Python313\Lib\dataclasses.py", line 1295, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
                          frozen, match_args, kw_only, slots,
                          weakref_slot)
  File "C:\Users\keepi\AppData\Local\Programs\Python\Python313\Lib\dataclasses.py", line 1043, in _process_class
    raise TypeError('cannot inherit frozen dataclass from a '
                    'non-frozen one')
TypeError: cannot inherit frozen dataclass from a non-frozen one
PS C:\Users\keepi> ato --version
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\keepi\.local\bin\ato.exe\__main__.py", line 4, in <module>
    from atopile.cli.cli import cli
  File "C:\Users\keepi\pipx\venvs\atopile\Lib\site-packages\atopile\cli\cli.py", line 11, in <module>
    from . import build, configure, create, inspect, install, view
  File "C:\Users\keepi\pipx\venvs\atopile\Lib\site-packages\atopile\cli\build.py", line 10, in <module>
    import atopile.assertions
  File "C:\Users\keepi\pipx\venvs\atopile\Lib\site-packages\atopile\assertions.py", line 11, in <module>
    import pint
  File "C:\Users\keepi\pipx\venvs\atopile\Lib\site-packages\pint\__init__.py", line 18, in <module>
    from .delegates.formatter._format_helpers import formatter
  File "C:\Users\keepi\pipx\venvs\atopile\Lib\site-packages\pint\delegates\__init__.py", line 12, in <module>
    from . import txt_defparser
  File "C:\Users\keepi\pipx\venvs\atopile\Lib\site-packages\pint\delegates\txt_defparser\__init__.py", line 12, in <module>
    from .defparser import DefParser
  File "C:\Users\keepi\pipx\venvs\atopile\Lib\site-packages\pint\delegates\txt_defparser\defparser.py", line 10, in <module>
    from . import block, common, context, defaults, group, plain, system
  File "C:\Users\keepi\pipx\venvs\atopile\Lib\site-packages\pint\delegates\txt_defparser\common.py", line 23, in <module>
    @dataclass(frozen=True)
     ~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\keepi\AppData\Local\Programs\Python\Python313\Lib\dataclasses.py", line 1295, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
                          frozen, match_args, kw_only, slots,
                          weakref_slot)
  File "C:\Users\keepi\AppData\Local\Programs\Python\Python313\Lib\dataclasses.py", line 1043, in _process_class
    raise TypeError('cannot inherit frozen dataclass from a '
                    'non-frozen one')
TypeError: cannot inherit frozen dataclass from a non-frozen one
```

**Comment by mawildoer** [comment]
Thanks @markwu2001 ! This is caused by the same version issue with `pint` as your other issues: https://github.com/atopile/atopile/issues/491#issuecomment-2434232100

Installing with `python3.12` (until the updated `pint` is released) should fix it!
