### ISSUE TITLE
"ato create" throws exception in version 0.2.66

### ISSUE THREAD

**Issue by markwu2001** [atopile/atopile#491]
Cannot run "ato create"
```
mark@Marks-MacBook-Pro GitHub % ato create
Traceback (most recent call last):
  File "/Users/mark/.local/bin/ato", line 5, in <module>
    from atopile.cli.cli import cli
  File "/Users/mark/.local/pipx/venvs/atopile/lib/python3.13/site-packages/atopile/cli/cli.py", line 11, in <module>
    from . import build, configure, create, inspect, install, view
  File "/Users/mark/.local/pipx/venvs/atopile/lib/python3.13/site-packages/atopile/cli/build.py", line 10, in <module>
    import atopile.assertions
  File "/Users/mark/.local/pipx/venvs/atopile/lib/python3.13/site-packages/atopile/assertions.py", line 11, in <module>
    import pint
  File "/Users/mark/.local/pipx/venvs/atopile/lib/python3.13/site-packages/pint/__init__.py", line 18, in <module>
    from .delegates.formatter._format_helpers import formatter
  File "/Users/mark/.local/pipx/venvs/atopile/lib/python3.13/site-packages/pint/delegates/__init__.py", line 12, in <module>
    from . import txt_defparser
  File "/Users/mark/.local/pipx/venvs/atopile/lib/python3.13/site-packages/pint/delegates/txt_defparser/__init__.py", line 12, in <module>
    from .defparser import DefParser
  File "/Users/mark/.local/pipx/venvs/atopile/lib/python3.13/site-packages/pint/delegates/txt_defparser/defparser.py", line 10, in <module>
    from . import block, common, context, defaults, group, plain, system
  File "/Users/mark/.local/pipx/venvs/atopile/lib/python3.13/site-packages/pint/delegates/txt_defparser/common.py", line 23, in <module>
    @dataclass(frozen=True)
     ~~~~~~~~~^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/dataclasses.py", line 1295, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
                          frozen, match_args, kw_only, slots,
                          weakref_slot)
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/dataclasses.py", line 1043, in _process_class
    raise TypeError('cannot inherit frozen dataclass from a '
                    'non-frozen one')
TypeError: cannot inherit frozen dataclass from a non-frozen one
```
Ato Version from pipx:
```
mark@Marks-MacBook-Pro ~ % pipx list
venvs are in /Users/mark/.local/pipx/venvs
apps are exposed on your $PATH at /Users/mark/.local/bin
manual pages are exposed at /Users/mark/.local/share/man
   package atopile 0.2.66, installed using Python 3.13.0
    - ato
mark@Marks-MacBook-Pro ~ % 
```

**Comment by mawildoer** [comment]
Thanks for the heads up @markwu2001 !

Seems this is a problem with `pint`. There's an issue here on their github repo and a fix should be out on their end soon: https://github.com/hgrecco/pint/issues/2065

In the meantime, you can use python3.12 instead by installing with `pipx install atopile --python python3.12`
